---
title: "writing_functions"
author: "Mukta Patwari"
date: "2025-10-23"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Start small

z-scores

```{r}
x_vec = rnorm(20, mean = 10, sd = 3.5)

(x_vec - mean(x_vec)) / sd(x_vec)
```

Function to compute z scores

```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)) {
    stop("The input x should be numeric")
  }
  
  if (length(x) < 5) {
    stop("Only compute z scores when the input has 5 or more numbers")
  }
  
  z = (x - mean(x)) / sd(x)
  
  z
}
```

Let's try our function...

```{r}
z_scores(x = x_vec)

num_vec = rnorm(123, mean = 14, sd = 0.4)

z_scores(x = num_vec)
```

Let's break our function

```{r, error = TRUE}
z_scores(3)

z_scores("my name is Mukta")
```

## Computing

Compute and return mean and SD of a numeric vector

```{r}
mean_and_sd = function() {
  
  if (!is.numeric(x)) {
    stop("The input x should be numeric")
  }
  
  if (length(x) < 5) {
    stop("Only compute z scores when the input has 5 or more numbers")
  }
  
  
  mean_x = mean(x, na.rm = TRUE)
  sd_x = sd(x, na.rm = TRUE)
  
  tibble(
    mean - mean_x,
    sd = sd_x
  )
}
```

